import pandas as pd
from pathlib import Path

replacements = [
    ["'S", "'s"],
    [" Of ", " of "],
    [" On ", " on "],
    [" The ", " the "],
    [" And ", " and "],
    [" For ", " for "],
    [" With ", " with "],
]

depts = [
    "01 - OFFICE OF THE MAYOR",
    "03 - OFFICE OF THE INSPECTOR GENERAL",
    "05 - BUDGET AND MANAGEMENT",
    "06 - TECHNOLOGY AND INNOVATION",
    "15 - CITY COUNCIL",
    "21 - DEPARTMENT OF HOUSING",
    "23 - CULTURAL AFFAIRS AND SPECIAL EVENTS",
    "25 - CITY CLERK",
    "27 - FINANCE",
    "28 - CITY TREASURER'S OFFICE",
    "29 - DEPARTMENT OF REVENUE",
    "30 - ADMINISTRATIVE HEARINGS",
    "31 - LAW",
    "32 - OFFICE OF COMPLIANCE",
    "33 - HUMAN RESOURCES",
    "35 - PROCUREMENT SERVICES",
    # "38 - ASSETS, INFORMATION, AND SERVICES (AIS)", ?????????
    # "38 - GENERAL SERVICES",
    "38 - FLEET & FACILITY MANAGEMENT",
    "39 - BOARD OF ELECTIONS COMMISSIONERS",
    "40 - DEPARTMENT OF FLEET MANAGEMENT",
    "41 - HEALTH",
    "45 - COMMISSION ON HUMAN RELATIONS",
    "48 - MAYOR'S OFFICE FOR PEOPLE WITH DISABILITIES",
    "50 - FAMILY & SUPPORT SERVICES",
    "51 - PUBLIC SAFETY ADMINSTRATION",
    "54 - PLANNING AND DEVELOPMENT",
    "55 - CHICAGO POLICE BOARD",
    "56 - INDEPENDENT POLICE REVIEW AUTHORITY (IPRA)",
    "57 - CHICAGO POLICE DEPARTMENT",
    "58 - EMERGENCY MANAGEMENT COMMUNICATION",
    "59 - CHICAGO FIRE DEPARTMENT",
    "60 - CIVILIAN OFFICE OF POLICE ACCOUNTABILITY",
    "62 - COMMUNITY COMMISION FOR PUBLIC SAFETY AND ACCOUNTABILITY",
    "67 - BUILDINGS",
    "70 - BUSINESS AFFAIRS AND CONSUMER PROTECTION",
    "72 - ENVIRONMENT",
    "73 - ANIMAL CARE & CONTROL",
    "77 - LICENSE APPEAL COMMISSION",
    "78 - BOARD OF ETHICS",
    "81 - STREETS AND SANITATION",
    "84 - CHICAGO DEPARTMENT OF TRANSPORTATION",
    "85 - AVIATION",
    "88 - WATER MANAGEMENT",
    "91 - PUBLIC LIBRARY",
    "99 - FINANCE GENERAL",
]

accounts = [
    "0000 - Personnel Services",
    "0003 - Scheduled Wage Adjustments",
    "0005 - Salaries and Wages - on Payroll",
    "0006 - Salary Provision",
    "0008 - For Payment of Retroactive Salaries",
    "0012 - Contract Wage Increment - Prevailing Rate",
    "0015 - Schedule Salary Adjustments",
    "0017 - Wage Allowance for Aldermanic Ward Staff (up to Four Full-Time Salaried Employees Per Alderman)",
    "0020 - Overtime",
    "0021 - Sworn/Civilian Holiday Premium Pay",
    "0022 - Duty Availability",
    "0024 - Compensatory Time Payment",
    "0027 - Supervisors Quarterly Payment",
    "0028 - Cooperative Education Program",
    "0029 - For Health Maintenance Organization Premiums (HMO) Provided to Eligible Employees and Their Families",
    "0032 - Reimbursable Overtime",
    "0039 - For the Employment of Students as Trainees",
    "0042 - CLAIMS AND ADMIN FOR HOSP AND MED CARE PROVIDED TO ELIGIBLE EMPLOYEES",
    "0043 - HMO PREM, CLAIMS, AND ADMIN FOR SWORN POLICE AND FIRE ON DUTY/OCCUP DISABILITY",
    "0044 - Fringe Benefits",
    "0045 - For the Cost of Claims and Administration or Premiums for Term Life Insurance",
    "0049 - Claims and Costs of Administration Pursuant to the Workers' Compensation Act",
    "0050 - Stipends",
    "0051 - Claims Under Unemployment Insurance Act",
    "0052 - Costs of Claims and Administration for Hospital and Medical Care to Eligible Annuitants and Their Eligible Dependents",
    "0055 - Extra Hire",
    "0056 - For the Cost of Claims and Administration or Premiums for a Co-Insured Dental Plan for Employees",
    "0060 - Specialty Pay",
    "0061 - Driver's Differential",
    "0062 - Required Certifications",
    "0063 - Fitness Benefit",
    "0070 - Tuition Reimbursement and Educational Programs",
    "0085 - City Deferred Compensation Contributions for Union Members",
    "0088 - Furlough/Supervisors Compensation Time Buy-Back",
    "0091 - Uniform Allowance",
    "0095 - For Payment of Allowances of Money to Families or Dependents of Policemen or Firemen Fatally Injured While in the Performance of Their Duties",
    "0096 - 1-YEAR SALARY FOR SWORN POLICE OR FIRE MEMBER KILLED IN THE LINE OF DUTY",
    "0100 - Contractual Services",
    "0123 - For Services Provided by Performers and Exhibitors",
    "0124 - Investigation Costs",
    "0125 - Office and Building Services",
    "0126 - Office Conveniences",
    "0128 - Investigation Costs. To Be Expended at the Direction of the Comptroller",
    "0130 - Postage",
    "0135 - For Delegate Agencies",
    "0138 - For Professional Services for Information Technology Maintenance",
    "0139 - For Professional Services for Information Technology Development",
    "0140 - For Professional and Technical Services and Other Third Party Benefit Agreements",
    "0141 - Appraisals",
    "0142 - Accounting and Auditing",
    "0143 - Court Reporting",
    "0144 - Engineering and Architecture",
    "0145 - Legal Expenses",
    "0147 - Surveys",
    "0148 - Testing and Inspecting",
    "0149 - For Software Maintenance and Licensing",
    "0150 - Publications and Reproduction - Outside Services. To be Expended with the Prior Approval of Graphics Services",
    "0152 - Advertising",
    "0153 - Promotions",
    "0154 - For the Rental and Maintenance of Data Processing, Office Automation and Data Communications Hardware",
    "0155 - Rental of Property",
    "0156 - Lock Box Rental",
    "0157 - Rental of Equipment and Services",
    "0159 - Lease Purchase Agreements for Equipment and Machinery",
    "0160 - Repair or Maintenance of Property",
    "0161 - Operation, Repair or Maintenance of Facilities",
    "0162 - Repair/Maintenance of Equipment",
    "0163 - Repair/Maintenance of Streets and Pavements",
    "0164 - Bookbinding",
    "0165 - Graphic Design Services",
    "0166 - Dues, Subscriptions and Memberships",
    "0168 - Educational Development through Cooperative Education Program and Apprenticeship Program",
    "0169 - Technical Meeting Costs",
    "0170 - Surety Bond Premiums",
    "0171 - Miscellaneous Supplies",
    "0172 - For the Cost of Insurance Premiums and Expenses",
    "0176 - Maintenance and Operation of City Owned Vehicles",
    "0178 - Freight and Express Charges",
    "0179 - Messenger Service",
    "0181 - Mobile Communication Services",
    "0183 - Water",
    "0185 - Waste Disposal Services",
    "0188 - Vehicle Tracking Service",
    "0189 - Telephone - Non-Centrex Billings",
    "0190 - Telephone - Centrex Billings",
    "0191 - Telephone - Relocations of Phone Lines",
    "0196 - Data Circuits",
    "0197 - Telephone - Maintenance and Repair of Equipment and Voicemail",
    "0228 - Out of Town Travel for Auditors Only",
    "0229 - Transportation and Expense Allowance",
    "0245 - Reimbursement to Travelers",
    "0270 - Local Transportation",
    "0300 - Commodities and Materials",
    "0312 - Software Purchases",
    "0313 - Cleaning and Sanitation Supplies",
    "0314 - Fuel Oil",
    "0315 - Motor Vehicle Diesel Fuel",
    "0316 - Gas - Bottled and Propane",
    "0318 - Other Fuel",
    "0319 - Clothing",
    "0320 - Gasoline",
    "0322 - Natural Gas",
    "0325 - Alternative Fuel",
    "0330 - Food",
    "0331 - Electricity",
    "0332 - Electricity - Street Lighting",
    "0338 - License Sticker, Tag and Plates",
    "0339 - Revenue Stamps",
    "0340 - Material and Supplies",
    "0341 - Chemicals",
    "0342 - Drugs, Medicine and Chemical Materials",
    "0345 - Apparatus and Instruments",
    "0348 - Books and Related Material",
    "0350 - Stationery and Office Supplies",
    "0360 - Repair Parts and Material",
    "0361 - Building Materials and Supplies",
    "0362 - Paints and Painting Supplies",
    "0364 - Plumbing Supplies",
    "0365 - Electrical Supplies",
    "0400 - Equipment",
    "0401 - TOOLS LESS THAN OR EQUAL TO $100",
    "0402 - TOOLS GREATER THAN $100",
    "0410 - Equipment for Buildings",
    "0420 - Furniture and Fixtures",
    "0421 - Machinery and Equipment",
    "0422 - Office Machines",
    "0423 - Communication Devices",
    "0424 - Furniture and Furnishings",
    "0430 - Livestock",
    "0440 - Machinery and Equipment",
    "0445 - Technical and Scientific Equipment",
    "0446 - For the Purchase of IT and Data Communication Hardware",
    "0450 - Vehicles",
    "0451 - For Purchase of Vehicles for Use by the Police and Fire Departments",
    "0455 - For the Maintenance, Use, Benefit, and Enhancement of Emergency Response Vehicles",
    "0521 - Maintenance and Construction",
    "0526 - For the Maintenance, Use, Benefit, or Enhancement of Fire Stations and Training Facilities",
    "0540 - Construction of Buildings and Other Structures",
    "0700 - Contingencies",
    "0801 - Indirect Costs",
    "0902 - For Interest on Bonds",
    "0905 - For Payment to Metropolitan Sanitary District for Wastewater Services",
    "0912 - For Payment of Bonds",
    "0931 - For the Payment of Tort and Non-Tort Judgments, Outside Counsel Expenses and Expert Costs, as Approved by the Corporation Counsel",
    "0934 - Claims for Damages and Liabilities Against the City When Ordered Paid by the City Council",
    "0937 - For Cost and Administration of Hospital and Medical Expenses for Employees Injured on Duty Who Are Not Covered Under Workers' Compensation Act",
    "0943 - For Interest on Loans",
    "0944 - For Payment on Loans",
    "0955 - Interest on Library Financing",
    "0958 - For Payment of Water Pipe Extension Certificates",
    "0959 - For Bond Fees and Costs",
    "0960 - For Loss in Collection of Taxes",
    "0961 - For Payment of Term Notes",
    "0976 - For the City's Contribution to Employees' Annuity and Benefit Fund",
    "0982 - For Expense in Connection with Recognition and Awards to Citizens of Chicago for Acts of Heroism. To Be Expended on Order of the City Council",
    "0989 - For Refunds for Cancelled Voucher Warrants and Payroll Checks and for Refunding Duplicate Payments and Payments Made in Error",
    "0991 - To Provide for Matching and Supplementary Grant Funds Currently in Effect as Well as New Grants",
    "0992 - Tow Storage Refunds",
    "0999 - To Provide for Cultural Programming and Development Grants",
    "9005 - LEGAL FEES - COMMITTEE ON FINANCE",
    "9006 - For Legal Assistance to the City Council. To Be Expended at the Direction of the Chairman of the Committee on Finance",
    "9008 - ALDERMANIC EXPENSE ALLOWENCE",
    "9010 - FINANCE COMM PROF SERVICES",
    "9027 - For the City Contribution to Social Security Tax",
    "9046 - For Operations and Maintenance Reserve",
    "9047 - For Special Capital Projects Requiring Airline Approval, Excluding Airline Improvement Program",
    "9067 - For Physical Exams",
    "9072 - CITY COUNCIL CONTINGENT AND OTHER EXPENSES",
    "9076 - City's Contribution to Medicare Tax",
    "9097 - For Capital Construction",
    "9102 - Special Programs Costs",
    "9103 - Rehabilitation Loans and Grants",
    "9110 - Property Management, Maintenance and Security",
    "9112 - Property Maintenance Contract for the Harold Washington Library Center",
    "9121 - For Payment of Costs Associated with Lobbyist Activities on Behalf of the City of Chicago",
    "9142 - Returning Citizens Initiatives",
    "9143 - Workforce Services for Target Populations",
    "9148 - To Provide for Senior Citizens - Rebate of Sewer Services When Senior Occupies Multi-Family Residency or Condominium",
    "9160 - For Expenses Related to Services Provided by PBC",
    "9180 - For World Business Chicago Program",
    "9188 - For Expenses Related to the Operation of Millennium Park",
    "9189 - For Payment of the Annual Contribution to the Chicago Transit Authority (CTA)",
    "9199 - For Purchase of Chicago Public Library Books and Materials",
    "9204 - Youth Mentoring Programs",
    "9205 - For Distribution of the Net Proceeds of the Real Property Transfer Tax - CTA Portion",
    "9211 - SINGLE-FAMILY TROUBLED BUILDING INITIATIVE",
    "9212 - MULTI-FAMILY TROUBLED BUILDING INITIATIVE",
    "9213 - Affordable Housing Density Program",
    "9219 - Implementation of Cultural Plan",
    "9222 - Emergency Medical Transportation",
    "9224 - Micro Market Recovery Program",
    "9225 - Arts and Cultural Initiatives",
    "9241 - Criminal Justice Initiatives",
    "9253 - Early Childhood Education Program",
    "9254 - Violence Reduction Program",
    "9255 - Homeless Services for Youth",
    "9259 - Youth Employment",
    "9260 - After School Programs",
    "9261 - Children's Advocacy Center",
    "9262 - Earned Income Tax Credit",
    "9263 - Homeless Services",
    "9267 - Flexible Housing Pool",
    "9283 - CARE Pilot Program",
    "9287 - For Other Maintenance, Use, and Benefits for the Chicago Fire Department (CFD)",
    "9288 - For Expenses Related to Programming for Millennium Park",
    "9291 - Legal Protection Fund",
    "9295 - Consent Decree",
    "9296 - Reproductive Health Initiative",
    "9299 - Gender Based Violence Services",
    "9333 - Less Corporate Fund Savings",
    "9438 - For Services Provided by the Department of Fleet and Facilities Management",
    "9441 - For Services Provided by the Chicago Department of Public Health",
    "9454 - For Services Provided by the Department of Planning and Development",
    "9470 - For Services Provided by Business Affairs and Consumer Protection",
    "9481 - For Services Provided by the Department of Streets and Sanitation",
    "9484 - For Services Provided by the Chicago Department of Transportation",
    "9610 - To Reimburse Corporate Fund for Pension Payments",
    "9611 - To Reimburse the Corporate Fund for Indirect Costs Chargeable to Fund",
    "9635 - To Reimburse Midway Fund for Fire Department Salaries",
    "9636 - To Reimburse Midway Fund for Fire Department Benefits",
    "9640 - To Reimburse Corporate Fund for Costs Incurred for Collection of the Real Property Transfer Tax - CTA Portion",
    "9645 - To Reimburse the Corporate Fund for Indirect Pension Costs Chargeable to Fund",
    "9646 - American Rescue Plan Revenue Replacement",
    "9647 - Transfers Out",
    "9711 - Transfer to O'Hare Fund for Administrative Salaries",
    "9713 - Transfer to Specified Operating Funds for Administration",
    "9765 - Transfer for Contractual Services",
    "9771 - Transfer for Services Provided by the Department of Assets, Information, and Services",
    "9773 - Transfer for Services Provided by the Department of Police",
    "9774 - Transfer for Services Provided by the Office of Emergency Management and Communication",
    "9775 - Transfer for Services Provided by the Fire Department",
    "9776 - Transfer for Services Provided by the Department of Streets and Sanitation",
    "9778 - Transfer for Services Provided by the Chicago Department of Aviation",
    "9803 - For Programming and Marketing",
    "9805 - For Festival Production",
    "9807 - For Redemption Expenses",
    "9813 - For Local Promotions and Marketing",
    "9980 - Municipal Fund Pension Allocation",
    "9981 - Laborers' Fund Pension Allocation",
    "9982 - Policemen's Fund Pension Allocation",
    "9983 - Firemen's Fund Pension Allocation",
    "9984 - Municipal Fund Advance Pension Payment",
    "9985 - Laborers' Fund Advance Pension Payment",
    "9986 - Policemen's Fund Advance Pension Payment",
    "9987 - Firemen's Fund Advance Pension Payment",
    "N/A - Restoration Committee",
]

fundsCodes = [
    "0B09 - CTA Real Property Transfer Tax Fund",
    "0B21 - Tax Increment Financing Administration Fund",
    "0B25 - Chicago Police CTA Detail Fund",
    "0B26 - Chicago Parking Meters Fund",
    "0B32 - Garbage Collection Fund",
    "0B42 - Foreign Fire Insurance Tax Fund",
    "0B53 - Wheelchair Accessible Vehicle Fund",
    "0B64 - Cable Local Origination Fund",
    "0B67 - Protecting CARE Fund",
    "0B70 - Cannabis Regulation Tax",
    "0B89 - Opioid Settlement Fund",
    "0B90 - Vaping Settlement Fund",
    "0B92 - Construction and Demolition Debris Management Fund",
    "0B93 - Houseshare Surcharge - Homeless Services Fund",
    "0B94 - Houseshare Surcharge - Domestic Violence Fund",
    "0D43 - Neighborhoods Opportunity Fund",
    "0D44 - Citywide Adopt-a-landmark Fund",
    "0D45 - Local Impact Fund",
    "925C - COVID-19 Grant Fund",
    "925D - Disaster Recovery Fund",
    "925E - Entitlement Fund",
    "925F - Federal Grant Fund",
    "925L - Local Public and Private Grant Fund",
    "925P - Program Income Fund",
    "925S - State Grant Fund",
    "0075 - Grants Management Fund",
    "0100 - Corporate Fund",
    "0200 - Water Fund",
    "0300 - Vehicle Tax Fund",
    "0310 - Motor Fuel Tax Fund",
    "0314 - Sewer Fund",
    "0346 - Library Fund",
    "0353 - Emergency Communication Fund",
    "0355 - Special Events and Municipal Hotel Operators' Occupation Tax Fund",
    "0510 - Bond Redemption and Interest Series Fund",
    "0521 - Library Property Tax Levy Fund",
    "0610 - Chicago Midway Airport Fund",
    "0681 - Municipal Employees' Annuity and Benefit Fund",
    "0682 - Laborers' and Retirement Board Annuity and Benefit Fund",
    "0683 - Policemen's Annuity and Benefit Fund",
    "0684 - Firemen's Annuity and Benefit Fund",
    "0740 - O'HARE REVENUE FUND",
    "0994 - Controlled Substances Fund",
    "0996 - Affordable Housing Opportunity Fund",
    "GA00 - Coronavirus Local Fiscal Recovery Fund",
]

categories = {
    "City Development": ["21", "23", "54"],
    "Infrastructure Services": ["81", "84", "85", "88"],
    "Community Services": ["41", "45", "48", "50", "91", "32"],
    "Legislative & Elections": ["15", "39"],
    "Finance & Administration": [
        "01",
        "05",
        "06",
        "25",
        "27",
        "28",
        "30",
        "31",
        "33",
        "35",
        "38",
        "40",
        "29",
    ],
    "Public Safety": ["51", "55", "56", "57", "58", "59", "60", "62"],
    "General Financing": ["99"],
    "Regulatory": ["03", "67", "70", "72", "73", "77", "78"],
}


def cleanTitle(row):
    row = row.title()
    for replacement in replacements:
        row = row.replace(*replacement)
    return row


def makeCSV(ls, fileName, columns, titleCase=False):
    df = pd.DataFrame(ls).sort_values(by=[0])
    df.columns = columns
    df = df.set_index(columns[0])
    series = df[columns[1]]

    if titleCase:
        series = series.apply(cleanTitle)

    series.to_csv(f"./python/labels/{fileName}.csv")
    series.to_csv(f"./page/data/{fileName}.csv")
    return series


def splitList(ls, fileName, columns, titleCase=False):
    makeCSV(list(map(lambda x: x.split(" - ", 1), ls)), fileName, columns, titleCase)


def labelData():
    Path("labels").mkdir(parents=True, exist_ok=True)
    Path("./page/data").mkdir(parents=True, exist_ok=True)

    # match categories
    categoryMatches = []
    for key, value in categories.items():
        for code in value:
            categoryMatches.append([code, key])

    splitList(depts, "depts", ["deptNum", "deptName"], True)
    splitList(
        accounts,
        "accounts",
        ["accountNum", "accountName"],
    )
    splitList(fundsCodes, "fundCodes", ["fundNum", "fundName"])
    makeCSV(categoryMatches, "categories", ["deptNum", "category"])
